### ISSUE TITLE
Not loading (please help?)

### ISSUE THREAD

**Issue by Cookie367** [angelolz1/CookieClickerRPC#5]
Hello, my browser extension isn't loading. It says "Your Rich Presence will show once the Cookie Clicker mod is loaded." but it's for like 15 minutes and still doesn't work... Why?

**Comment by angelolz1** [comment]
Hey there!

What browser and OS are you using?

Also, have you made sure that you loaded the mod properly with the instructions [here](https://github.com/angelolz1/CookieClickerRPC#running-the-program)?

**Comment by r1zyn** [comment]
If you go onto the Cookie Clicker tab, open the JavaScript console via inspect element (ctrl + shift + i) and paste the code `Game.LoadMod('https://angelolz.dev/mods/ccrpc/main.js');` into the console and run it, the mod should load

**Comment by r1zyn** [comment]
> If you go onto the Cookie Clicker tab, open the JavaScript console via inspect element (ctrl + shift + i) and paste the code `Game.LoadMod('https://angelolz.dev/mods/ccrpc/main.js');` into the console and run it, the mod should load

Also I'm not sure if this is supposed to happened automatically but I also waited for a bit and nothing happened and I was really confused, took me a while to figure this out (by experimenting) so maybe updating the documentation may be a bit helpful

I still don't understand this part either
> Copy this code and save it as a bookmark.

**Comment by angelolz1** [comment]
Honestly, I was aiming for a one-click mod install with the bookmark method. It looks something like this:
![image](https://user-images.githubusercontent.com/25342763/213084700-9a046a08-fb4a-471e-afdb-63123569dbaf.png)

But I think just running the small javascript function in console might be easier. I will update the readme with these instructions. Thank you for your feedback!

**Comment by angelolz1** [comment]
As the original poster of this issue has not responded to me, I will close this issue for now. If issue still exists, feel free to open this issue again and post another comment.

Thank you for using my mod!
